actual jooat implementation instead of hooking rage::atStringHash
scripthookvdotnet/scripthookvdotnet pull request #1130
Opened 2023-01-15 09:55 UTC by 0x-FADED

- why hook `rage::atStringHash(const char*,uint)` when we can have actual jooat implementation
- the code is from here: https://gtaforums.com/topic/879408-c-string-hasher/ from `Fireboyd78`

2023-01-15 12:48 UTC, kagikn requested changes
Sorry, but this PR misses the edge case for double quotes. If the first byte is `0x22`, the function skips the first double quote and hash the string until another double quote or a null character is found. See #501 and search the exe for `48 8B 0B 33 D2 E8 ? ? ? ? 89 03` for more info.
I admit we didn't have to call `rage::atStringHash` since the calculation won't be changed in some game update (no changes between b372 and b2802 at least), though.

In terms of my comments for naming convention for C#, you might want to see [coding conventions in C# documentation](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions). For naming conventions, I think @crosire should review this PR as well.

2023-01-15 12:48 UTC, kagikn commented on source/core/joaat.cs
> +	public static class atStringHash
We name classes using Pascal casing so, this should be `AtStringHash`.

2023-01-15 12:48 UTC, kagikn commented on source/core/joaat.cs
> +		private static uint atPartialStringHash(string str, uint initialHash)
We also name methods using Pascal casing.

2023-01-15 17:07 UTC, kagikn approved these changes
Fair enough. If I find any occurrences with strings whose first string is a double quote, I'll add code for the edge case. I haven't seen that occurrences actually.

2023-01-17 18:55 UTC, crosire commented
I'm nore sure I see the benefit? I guess we save us a string copy and pin. But it was kinda nice to just have the game do the heavy lifting and not worry about the implementation details.

2023-01-18 13:03 UTC, kagikn requested changes
I forgot to say this, but strings (which is UTF-16 in .NET) should be encoded to UTF-8 just like before. GTA V uses UTF-8 and ASCII strings, but definitely not UTF-16 strings.
The current implementation throws exception if the string contains non-ASCII characters (`IndexOutOfRangeException`).

2023-01-18 13:24 UTC, kagikn commented
@crosire I'm not sure if you are saying we should not worry about the implementation details of the hashing function, but I can say this PR will improve performance (about 2x faster than before). Besides, I don't think they don't change how to calculate joaat hashes because even the equivalent function in GTA IV calculates in the same way (the function is at `0x5B1C30` in v1.0.7.0).

```
public static string RandomString(int length)
{
    const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_@";
    return new string(Enumerable.Repeat(chars, length)
                                .Select(s => s[randomInstForRandomStr.Next(s.Length)]).ToArray());
}

public static void MeasurePerformance()
{
    var randomStrs = new List<string>(10000000);
    for (int i = 0; i < 1000000; i++)
    {
        randomStrs.Add(RandomString(12));
    }

    var stopwatch = new Stopwatch();
    stopwatch.Start();
    foreach (var randomStr in randomStrs)
    {
        Game.GenerateHashOld(randomStr); // call rage::atStringHash via a delegate obtained via Marshal.GetDelegateForFunctionPointer (before this PR)
    }
    stopwatch.Stop();
    var oldElapsedTime = stopwatch.ElapsedMilliseconds;

    stopwatch.Reset();
    stopwatch.Start();
    foreach (var randomStr in randomStrs)
    {
        Game.GenerateHash(randomStr); // calculate the hash value by directly executing C# code (this PR)
    }
    stopwatch.Stop();
    var newElapsedTime = stopwatch.ElapsedMilliseconds;
}
```
In this code, `oldElapsedTime` will be twice as many as `newElapsedTime`. I guess calling a delegate consumes much more time when the delegate is obtained via `Marshal.GetDelegateForFunctionPointer()` than we would think.

2023-01-18 19:25 UTC, crosire commented
Fair. From an implementation point of view I'd just keep `NativeMemory.GetHashKey(string key) though and simply replace its definition, since the fancy concatenation overloads aren't used anyway:
```c#
static readonly byte[] LookupTable = { ... };

public static uint GetHashKey(string key)
{
	var bytes = Encoding.UTF8.GetBytes(key);
	uint hash = 0;
	for (int i = 0; i < str.Length; i++)
	{
		hash += LookupTable[bytes[i]];
		hash += (hash << 10);
		hash ^= (hash >> 6);
	}
	hash += (hash << 3);
	hash ^= (hash >> 11);
	hash += (hash << 15);
	return hash;
}
```

2023-01-19 22:46 UTC, Sardelka9515 commented
> I guess calling a delegate consumes much more time when the delegate is obtained via `Marshal.GetDelegateForFunctionPointer()` than we would think.

A bit irrelevant here, but i just figured that we can use the [function pointer syntax](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/function-pointers), just need to specify the calling convention (presumably Stdcall), maybe with the SuppressGCTransition attribute. Haven't tested yet, but it should work and be much faster.

2023-01-20 11:19 UTC, kagikn approved these changes
Fine by me regarding how to hash strings.

2023-01-20 13:11 UTC, kagikn commented
Sorry, but conflicts occur since I merged #1136.

2023-01-20 17:19 UTC, crosire commented
Would also prefer to ditch the new joaat.cs file and move the function definition back into the behemoth that is the `NativeMemory` class.

2023-01-20 20:14 UTC, closed without merging